/*
Copyright The Symphony Authors.

*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/yangyongzhi/sym-operator/pkg/apis/devops/v1"
	examplev1 "github.com/yangyongzhi/sym-operator/pkg/apis/example/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=devops.dmall.com, Version=v1
	case v1.SchemeGroupVersion.WithResource("migrates"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Devops().V1().Migrates().Informer()}, nil

		// Group=example.dmall.com, Version=v1
	case examplev1.SchemeGroupVersion.WithResource("foos"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Example().V1().Foos().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
