/*
Copyright The Symphony Authors.

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	migratev1 "github.com/yangyongzhi/sym-operator/pkg/apis/migrate/v1"
	versioned "github.com/yangyongzhi/sym-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/yangyongzhi/sym-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/yangyongzhi/sym-operator/pkg/client/listers/migrate/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MigrateInformer provides access to a shared informer and lister for
// Migrates.
type MigrateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MigrateLister
}

type migrateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMigrateInformer constructs a new informer for Migrate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMigrateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMigrateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMigrateInformer constructs a new informer for Migrate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMigrateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrateV1().Migrates(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MigrateV1().Migrates(namespace).Watch(options)
			},
		},
		&migratev1.Migrate{},
		resyncPeriod,
		indexers,
	)
}

func (f *migrateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMigrateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *migrateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&migratev1.Migrate{}, f.defaultInformer)
}

func (f *migrateInformer) Lister() v1.MigrateLister {
	return v1.NewMigrateLister(f.Informer().GetIndexer())
}
