/*
Copyright The Symphony Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/yangyongzhi/sym-operator/pkg/apis/migrate/v1"
	"github.com/yangyongzhi/sym-operator/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type MigrateV1Interface interface {
	RESTClient() rest.Interface
	FoosGetter
	MigratesGetter
}

// MigrateV1Client is used to interact with features provided by the migrate.dmall.com group.
type MigrateV1Client struct {
	restClient rest.Interface
}

func (c *MigrateV1Client) Foos(namespace string) FooInterface {
	return newFoos(c, namespace)
}

func (c *MigrateV1Client) Migrates(namespace string) MigrateInterface {
	return newMigrates(c, namespace)
}

// NewForConfig creates a new MigrateV1Client for the given config.
func NewForConfig(c *rest.Config) (*MigrateV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MigrateV1Client{client}, nil
}

// NewForConfigOrDie creates a new MigrateV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MigrateV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MigrateV1Client for the given RESTClient.
func New(c rest.Interface) *MigrateV1Client {
	return &MigrateV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MigrateV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
