/*
Copyright The Symphony Authors.

*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/yangyongzhi/sym-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Migrates returns a MigrateInformer.
	Migrates() MigrateInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Migrates returns a MigrateInformer.
func (v *version) Migrates() MigrateInformer {
	return &migrateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
