/*
Copyright The Symphony Authors.

*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// MigrateListerExpansion allows custom methods to be added to
// MigrateLister.
type MigrateListerExpansion interface{}

// MigrateNamespaceListerExpansion allows custom methods to be added to
// MigrateNamespaceLister.
type MigrateNamespaceListerExpansion interface{}
