/*
Copyright The Symphony Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/yangyongzhi/sym-operator/pkg/client/clientset/versioned/typed/migrate/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMigrateV1 struct {
	*testing.Fake
}

func (c *FakeMigrateV1) Foos(namespace string) v1.FooInterface {
	return &FakeFoos{c, namespace}
}

func (c *FakeMigrateV1) Migrates(namespace string) v1.MigrateInterface {
	return &FakeMigrates{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMigrateV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
