/*
Copyright The Symphony Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/yangyongzhi/sym-operator/pkg/apis/devops/v1"
	scheme "github.com/yangyongzhi/sym-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MigratesGetter has a method to return a MigrateInterface.
// A group's client should implement this interface.
type MigratesGetter interface {
	Migrates(namespace string) MigrateInterface
}

// MigrateInterface has methods to work with Migrate resources.
type MigrateInterface interface {
	Create(*v1.Migrate) (*v1.Migrate, error)
	Update(*v1.Migrate) (*v1.Migrate, error)
	UpdateStatus(*v1.Migrate) (*v1.Migrate, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Migrate, error)
	List(opts metav1.ListOptions) (*v1.MigrateList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Migrate, err error)
	MigrateExpansion
}

// migrates implements MigrateInterface
type migrates struct {
	client rest.Interface
	ns     string
}

// newMigrates returns a Migrates
func newMigrates(c *DevopsV1Client, namespace string) *migrates {
	return &migrates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the migrate, and returns the corresponding migrate object, and an error if there is any.
func (c *migrates) Get(name string, options metav1.GetOptions) (result *v1.Migrate, err error) {
	result = &v1.Migrate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migrates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Migrates that match those selectors.
func (c *migrates) List(opts metav1.ListOptions) (result *v1.MigrateList, err error) {
	result = &v1.MigrateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested migrates.
func (c *migrates) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("migrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a migrate and creates it.  Returns the server's representation of the migrate, and an error, if there is any.
func (c *migrates) Create(migrate *v1.Migrate) (result *v1.Migrate, err error) {
	result = &v1.Migrate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("migrates").
		Body(migrate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a migrate and updates it. Returns the server's representation of the migrate, and an error, if there is any.
func (c *migrates) Update(migrate *v1.Migrate) (result *v1.Migrate, err error) {
	result = &v1.Migrate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("migrates").
		Name(migrate.Name).
		Body(migrate).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *migrates) UpdateStatus(migrate *v1.Migrate) (result *v1.Migrate, err error) {
	result = &v1.Migrate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("migrates").
		Name(migrate.Name).
		SubResource("status").
		Body(migrate).
		Do().
		Into(result)
	return
}

// Delete takes name of the migrate and deletes it. Returns an error if one occurs.
func (c *migrates) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migrates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *migrates) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migrates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched migrate.
func (c *migrates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Migrate, err error) {
	result = &v1.Migrate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("migrates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
