/*
Copyright The Symphony Authors.

*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	migratev1 "github.com/yangyongzhi/sym-operator/pkg/client/clientset/versioned/typed/migrate/v1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	MigrateV1() migratev1.MigrateV1Interface
	// Deprecated: please explicitly pick a version if possible.
	Migrate() migratev1.MigrateV1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	migrateV1 *migratev1.MigrateV1Client
}

// MigrateV1 retrieves the MigrateV1Client
func (c *Clientset) MigrateV1() migratev1.MigrateV1Interface {
	return c.migrateV1
}

// Deprecated: Migrate retrieves the default version of MigrateClient.
// Please explicitly pick a version.
func (c *Clientset) Migrate() migratev1.MigrateV1Interface {
	return c.migrateV1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.migrateV1, err = migratev1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.migrateV1 = migratev1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.migrateV1 = migratev1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
